# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apache-ctrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from subprocess import call, DEVNULL, STDOUT
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1150, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/logo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        fontDB = QtGui.QFontDatabase()
        fontID = fontDB.addApplicationFont(":/assets/comfortaa.ttf")
        comforta_ttf_font = QtGui.QFont("Comfortaa", 14, 1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left = QtWidgets.QFrame(self.background)
        self.frame_left.setMinimumSize(QtCore.QSize(800, 600))
        self.frame_left.setToolTipDuration(-1)
        self.frame_left.setStyleSheet("")
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setContentsMargins(120, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_buttons = QtWidgets.QFrame(self.frame_left)
        self.frame_buttons.setMaximumSize(QtCore.QSize(660, 540))
        self.frame_buttons.setStyleSheet("")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_buttons.setMidLineWidth(0)
        self.frame_buttons.setObjectName("frame_buttons")
        self.blueButton = QtWidgets.QPushButton(self.frame_buttons)
        self.blueButton.setGeometry(QtCore.QRect(0, 420, 220, 110))
        font = comforta_ttf_font
        font.setPointSize(24)
        self.blueButton.setFont(font)
        self.blueButton.setAutoFillBackground(False)
        self.blueButton.setStyleSheet("border-radius: 22px;\n"
"background-color: #0100ec;\n"
"color: rgb(255, 255, 255);")
        self.blueButton.setFlat(False)
        self.blueButton.setObjectName("blueButton")
        self.redButton = QtWidgets.QPushButton(self.frame_buttons)
        self.redButton.setGeometry(QtCore.QRect(440, 420, 220, 110))
        font = comforta_ttf_font
        font.setPointSize(24)
        self.redButton.setFont(font)
        self.redButton.setAutoFillBackground(False)
        self.redButton.setStyleSheet("border-radius: 22px;\n"
"background-color: #fe0000;\n"
"color: rgb(255, 255, 255);\n")
        self.redButton.setFlat(False)
        self.redButton.setObjectName("redButton")
        self.frame_logo = QtWidgets.QFrame(self.frame_buttons)
        self.frame_logo.setGeometry(QtCore.QRect(50, 20, 611, 161))
        self.frame_logo.setStyleSheet("background-image: url(:/assets/logo.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"border: none;")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.verticalLayout.addWidget(self.frame_buttons)
        self.frame_terminal = QtWidgets.QFrame(self.frame_left)
        self.frame_terminal.setMinimumSize(QtCore.QSize(0, 132))
        self.frame_terminal.setMaximumSize(QtCore.QSize(960, 132))
        self.frame_terminal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_terminal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_terminal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_terminal.setObjectName("frame_terminal")
        self.frame_terminal.hide()
        # Functions
        def activate():
            myCmd = 'pkexec /usr/local/bin/apache-ctrl.sh -i'
            out = os.popen(myCmd).read()
            showOutput(out)

        def deactivate():
            myCmd = 'pkexec /usr/local/bin/apache-ctrl.sh -t'
            out = os.popen(myCmd).read()
            showOutput(out)

        def enable():
            myCmd = 'pkexec /usr/local/bin/apache-ctrl.sh -e'
            out = os.popen(myCmd).read()
            showOutput(out)

        def disable():
            myCmd = 'pkexec /usr/local/bin/apache-ctrl.sh -d'
            out = os.popen(myCmd).read()
            showOutput(out)

        def showOutput(out):
            text = self.label_output.text()
            char = sum(1 for line in text)
            if str(out) == '':
                out = "Something went wrong, to see what it is please run from terminal.\n"
            else:
                print(out)

            result = str(text) + '> ' + str(out)
            height = char / 2
            if int(height) == 91:
                height = 0
            else:
                self.label_output.setGeometry(QtCore.QRect(10, 0, 660, 22 + int(height + 30)))

            self.label_output.setText(result)

        def showTerminal():
            if self.switchButton_show.isChecked():
                self.frame_terminal.show()
            else:
                self.frame_terminal.hide()

        def autostartState():
            out = call(['systemctl','is-enabled','httpd'],
                stdout=DEVNULL,
                stderr=STDOUT)
            if out == 0:
                self.switchButton.setChecked(True)
            else:
                self.switchButton.setChecked(False)

        def checkAutostart():
            if self.switchButton.isChecked():
                enable()
            else:
                disable()

        self.label_output = QtWidgets.QLabel(self.frame_terminal)
        self.label_output.setGeometry(QtCore.QRect(10, 0, 660, 22))
        self.label_output.setMinimumSize(QtCore.QSize(660, 22))
        self.label_output.setMaximumSize(QtCore.QSize(660, 127))
        self.label_output.setWordWrap(True)
        self.label_output.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.verticalLayout.addWidget(self.frame_terminal)
        self.horizontalLayout_2.addWidget(self.frame_left, 0, QtCore.Qt.AlignHCenter)
        self.frame_right = QtWidgets.QFrame(self.background)
        self.frame_right.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_right.setStyleSheet("")
        self.frame_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.label_options = QtWidgets.QLabel(self.frame_right)
        self.label_options.setGeometry(QtCore.QRect(56, 543, 91, 31))
        font = QtGui.QFont("Comfortaa", 16, 1)
        font.setPointSize(16)
        self.label_options.setFont(font)
        self.label_options.setAutoFillBackground(False)
        self.label_options.setObjectName("label_options")
        self.label_enable = QtWidgets.QLabel(self.frame_right)
        self.label_enable.setGeometry(QtCore.QRect(20, 600, 60, 22))
        font = QtGui.QFont("Comfortaa", 12, 1)
        font.setPointSize(12)
        self.label_enable.setFont(font)
        self.label_enable.setAutoFillBackground(False)
        self.label_enable.setObjectName("label_enable")
        self.label_disable = QtWidgets.QLabel(self.frame_right)
        self.label_disable.setGeometry(QtCore.QRect(120, 600, 62, 22))
        font = QtGui.QFont("Comfortaa", 12, 1)
        font.setPointSize(12)
        self.label_disable.setFont(font)
        self.label_disable.setAutoFillBackground(False)
        self.label_disable.setObjectName("label_disable")
        self.switchButton = QtWidgets.QPushButton(self.frame_right)
        self.switchButton.setGeometry(QtCore.QRect(80, 600, 41, 21))
        self.switchButton.setMaximumSize(QtCore.QSize(124, 101))
        self.switchButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/assets/off);\n"
"    background-position: center;\n"
"    background-repeat: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:checked {\n"
"    background-image: url(:/assets/on.png);\n"
"}")
        self.switchButton.setText("")
        self.switchButton.setCheckable(True)
        self.switchButton.setChecked(False)
        self.switchButton.setObjectName("switchButton")
        self.label_autostart = QtWidgets.QLabel(self.frame_right)
        self.label_autostart.setGeometry(QtCore.QRect(55, 577, 96, 22))
        font = comforta_ttf_font
        font.setPointSize(14)
        self.label_autostart.setFont(font)
        self.label_autostart.setAutoFillBackground(False)
        self.label_autostart.setObjectName("label_autostart")
        self.label_show = QtWidgets.QLabel(self.frame_right)
        self.label_show.setGeometry(QtCore.QRect(30, 630, 144, 22))
        font = comforta_ttf_font
        font.setPointSize(14)
        self.label_show.setFont(font)
        self.label_show.setAutoFillBackground(False)
        self.label_show.setObjectName("label_show")
        self.label_off = QtWidgets.QLabel(self.frame_right)
        self.label_off.setGeometry(QtCore.QRect(50, 653, 31, 22))
        font = QtGui.QFont("Comfortaa", 12, 1)
        font.setPointSize(12)
        self.label_off.setFont(font)
        self.label_off.setAutoFillBackground(False)
        self.label_off.setObjectName("label_off")
        self.switchButton_show = QtWidgets.QPushButton(self.frame_right)
        self.switchButton_show.setGeometry(QtCore.QRect(80, 653, 41, 21))
        self.switchButton_show.setMaximumSize(QtCore.QSize(124, 101))
        self.switchButton_show.setStyleSheet("QPushButton {\n"
"    background-image: url(:/assets/off.png);\n"
"    background-position: center;\n"
"    background-repeat: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:checked {\n"
"    background-image: url(:/assets/on.png);\n"
"}")
        self.switchButton_show.setText("")
        self.switchButton_show.setCheckable(True)
        self.switchButton_show.setChecked(False)
        self.switchButton_show.setObjectName("switchButton_show")
        self.label_on = QtWidgets.QLabel(self.frame_right)
        self.label_on.setGeometry(QtCore.QRect(120, 653, 31, 22))
        font = QtGui.QFont("Comfortaa", 12, 1)
        font.setPointSize(12)
        self.label_on.setFont(font)
        self.label_on.setAutoFillBackground(False)
        self.label_on.setObjectName("label_on")
        self.horizontalLayout_2.addWidget(self.frame_right)
        self.horizontalLayout.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)

        # Function Calls
        self.blueButton.clicked.connect(activate)
        self.redButton.clicked.connect(deactivate)

        self.switchButton.clicked.connect(checkAutostart)
        self.switchButton_show.clicked.connect(showTerminal)

        autostartState()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ApacheServerControl"))
        self.blueButton.setText(_translate("MainWindow", "Activate"))
        self.redButton.setText(_translate("MainWindow", "Deactivate"))
        self.label_output.setText(_translate("MainWindow", "> ... \n"))
        self.label_options.setText(_translate("MainWindow", "Options"))
        self.label_enable.setText(_translate("MainWindow", "Disable"))
        self.label_disable.setText(_translate("MainWindow", "Enable"))
        self.label_autostart.setText(_translate("MainWindow", "Autostart"))
        self.label_show.setText(_translate("MainWindow", "Show Terminal"))
        self.label_off.setText(_translate("MainWindow", "Off"))
        self.label_on.setText(_translate("MainWindow", "On"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
